export {default as AdminLoginPage} from './login/Page';
export {default as AdminDashboardPage} from './dashboard/Page';
export { RegisterProfessionalPage} from './profesionales/RegisterProfessional';
export {default as ConfigurationPage} from './configuracion/Page';
export { RegisterHealthUserPage } from './usuarios/RegisterHealthUser';
export { RegisterAdminPage } from './administradores/RegisterAdmin';
export { HealthProfessionalList } from './profesionales/HealthProfessionalList';
export { HealthUsersList} from './usuarios/HealthUserList';
export { AdminsList} from './administradores/AdminUserList';
export { ClinicDetails} from './clinica/ClinicaDetail';